name: Dispatch Test

on:
  workflow_dispatch:
    inputs:
      foo_bar:
        description: test input
        required: true
        default: "thebigone.gg"
        type: string
      bar_baz:
        description: second input
        required: true
        default: "www.thebigone.gg"
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "foo_bar=${{ github.event.inputs.foo_bar }}"
          echo "bar_baz=${{ github.event.inputs.bar_baz }}"
