name: Dispatch Test

on:
  workflow_dispatch:
    inputs:
      foo_bar:
        description: test input
        required: true
        default: "thebigone.gg"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "foo_bar=${{ github.event.inputs.foo_bar }}"
