name: Dispatch Test

on:
  workflow_dispatch:
    inputs:
      foo:
        description: test input
        required: true
        default: "bar"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "foo=${{ github.event.inputs.foo }}"

